# Scripts
alias check-weather='$HOME/Documents/linux_docs/scripts/check_weather.sh'
alias chmod-scripts='chmod +x $HOME/Documents/linux_docs/scripts/chmod_scripts.sh && $HOME/Documents/linux_docs/scripts/chmod_scripts.sh'
alias create-swapfile='$HOME/Documents/linux_docs/scripts/create_swapfile.sh'
alias dos2unix-converter='$HOME/Documents/linux_docs/scripts/dos2unix_converter.sh'
alias export-smart-info='$HOME/Documents/linux_docs/scripts/export_smart_info.sh'
alias git-clone-repo='$HOME/Documents/linux_docs/scripts/git_clone_repo.sh'
alias remove-snap='$HOME/Documents/linux_docs/scripts/remove_snap.sh'
alias remove-swapfile='$HOME/Documents/linux_docs/scripts/remove_swapfile.sh'
alias replace-text='$HOME/Documents/linux_docs/scripts/replace_text.sh'
alias shellcheck-scripts='$HOME/Documents/linux_docs/scripts/shellcheck_scripts.sh'
alias snake-case-converter='$HOME/Documents/linux_docs/scripts/snake_case_converter.sh'
alias sync-backup-drives='$HOME/Documents/linux_docs/scripts/sync_backup_drives.sh'
alias sync-bashrc-configs='$HOME/Documents/linux_docs/scripts/sync_bashrc_configs.sh'
alias sync-boot-images='$HOME/Documents/linux_docs/scripts/sync_boot_images.sh'
alias sync-custom='$HOME/Documents/linux_docs/scripts/sync_custom.sh'
alias sync-linux-docs='$HOME/Documents/linux_docs/scripts/sync_linux_docs.sh'
alias tab-space-converter='$HOME/Documents/linux_docs/scripts/tab_space_converter.sh'
alias universal-distro-setup='$HOME/Documents/linux_docs/scripts/universal_distro_setup.sh'

# BTRFS
alias balance='sudo btrfs balance start'
alias balance-cancel='sudo btrfs balance cancel'
alias balance-pause='sudo btrfs balance pause'
alias balance-resume='sudo btrfs balance resume'
alias balance-status='sudo btrfs balance status'
alias defrag='sudo btrfs filesystem defragment -rv'
alias fsusage='sudo btrfs filesystem usage'
alias ratio='sudo compsize -x'
alias scrub='sudo btrfs scrub start'
alias scrub-cancel='sudo btrfs scrub cancel'
alias scrub-resume='sudo btrfs scrub resume'
alias scrub-status='sudo btrfs scrub status'

# Packages
if ! command -v protontricks >/dev/null 2>&1 && flatpak list --columns=app | grep -Fiq com.github.Matoking.protontricks; then
    alias protontricks='flatpak run com.github.Matoking.protontricks'
    alias protontricks-launch='flatpak run --command=protontricks-launch com.github.Matoking.protontricks'
fi
alias waystop='waydroid session stop'

# Other
alias cmdline='cat /proc/cmdline'
alias desktop='echo $XDG_CURRENT_DESKTOP'
alias diskinfo='sudo smartctl -a'
alias mountcheck='sudo findmnt --verify --verbose'
alias path='echo "$PATH" | tr ":" "\n"'
alias sbash='source $HOME/.bashrc'
alias session='echo $XDG_SESSION_TYPE'
alias swappiness='cat /proc/sys/vm/swappiness'
alias uuid='lsblk -o name,uuid'
alias vm-parameters='sudo grep -R . /proc/sys/vm'
alias zswap-info='sudo grep -r . /sys/kernel/debug/zswap'
alias zswap-parameters='grep -R . /sys/module/zswap/parameters'
