Section "OutputClass"
    Identifier "AMD"
    MatchDriver "amdgpu"
    Driver "amdgpu"
EndSection

Section "Device"
    Identifier "AMD Device"
    Driver "amdgpu"
    Option "VariableRefresh" "true"
EndSection
