#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# Define text colors
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
reset=$(tput sgr0)

# Checks for directory
if [ -d /sys/firmware/efi ]; then
    boot_mode="uefi"
    echo "${green}Boot Mode: UEFI ${reset}"
else
    boot_mode="bios"
    echo "${green}Boot Mode: Legacy BIOS ${reset}"
fi
