#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# Define text colors
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
reset=$(tput sgr0)

# Define the boot drive
boot_drive="$(df / | tail -1 | awk '{print $1}')"

# Checks if a boot drive was detected
if [[ -z "$boot_drive" ]]; then
    echo "${red}No boot drive detected. ${reset}"
    exit 1
fi

# Checks if the device is an NVMe drive
if [[ $boot_drive == /dev/nvme* ]]; then

    # Extracts the parent NVMe device (without partition number)
    parent_device="${boot_drive//p[0-9]*/}"

    # Checks for NVMe specific information
    if [ -e "/sys/block/$(basename "$parent_device")/queue/rotational" ]; then

        if [ "$(cat "/sys/block/$(basename "$parent_device")/queue/rotational")" -eq 0 ]; then
            echo "${green}Boot Drive Detected: NVMe SSD ${reset}"
        else
            echo "${green}Boot Drive Detected: NVMe HDD (?) ${reset}"
        fi

    else
        echo "${red}Unknown drive type. ${reset}"
    fi

# Checks if the device is an eMMC storage
elif [[ $boot_drive == /dev/mmcblk* ]]; then
    echo "${green}Boot Drive Detected: eMMC ${reset}"

else
    # Checks for SATA and other block devices
    if [ -e "/sys/block/$(basename "$boot_drive")/queue/rotational" ]; then

        if [ "$(cat /sys/block/"$(basename "$boot_drive")"/queue/rotational)" -eq 0 ]; then
            echo "${green}Boot Drive Detected: SATA SSD ${reset}"
        else
            echo "${green}Boot Drive Detected: HDD ${reset}"
        fi

    else
        echo "${red}Unknown drive type. ${reset}"
    fi
fi
