#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# Define text colors
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
reset=$(tput sgr0)

# Define the operating system and convert it to lowercase
if [ -f /etc/os-release ]; then
    . /etc/os-release
    
    os="${ID:-unknown}"
    os_like="${ID_LIKE:-$os}"
    
    os=$(echo "${os:-unknown}" | tr '[:upper:]' '[:lower:]')
    os_like=$(echo "$os_like" | tr '[:upper:]' '[:lower:]')
    
    echo "${green}Detected Distro (ID): $os ${reset}"
    echo "${green}Detected Distro (ID_LIKE): $os_like ${reset}"
    
else
    echo "${red}Unable to detect the operating system. ${reset}"
    exit 1
fi

# List of packages
packages=(
"package1"
"package2"
)

aur_packages=(
"aur-package1"
"aur-package2"
)

flatpaks=(
"flatpak1"
"flatpak2"
)

# Executes commands based on the operating system
case "$os" in
    "arch")
        sudo pacman -S --needed --noconfirm "${packages[@]}"
        ;;
    "debian"|"ubuntu")
        sudo apt-get install -y "${packages[@]}"
        ;;
    "fedora"|"openmandriva")
        sudo dnf install -y "${packages[@]}"
        ;;
    "opensuse"*)
        sudo zypper in -y "${packages[@]}"
        ;;
    "solus")
        sudo eopkg install -y "${packages[@]}"
        ;;
    "void")
        sudo xbps-install -Sy "${packages[@]}"
    *)
        case "$os_like" in
            "arch")
                sudo pacman -S --needed --noconfirm "${packages[@]}"
                ;;
            "debian"|"ubuntu debian")
                sudo apt-get install -y "${packages[@]}"
                ;;
            "fedora")
                sudo dnf install -y "${packages[@]}"
                ;;
            "opensuse"*)
                sudo zypper in -y "${packages[@]}"
                ;;
            "solus")
                sudo eopkg install -y "${packages[@]}"
                ;;
            "void")
                sudo xbps-install -Sy "${packages[@]}"
            *)
                echo "${red}Unsupported distribution. ${reset}"
                exit 1
                ;;
        esac
        ;;
esac
