#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# Text formatting
red=$(tput setaf 1)
yellow=$(tput setaf 3)
reset=$(tput sgr0)

# Detect the operating system
if [ -f /etc/os-release ]; then
    . /etc/os-release
    os="${ID:-unknown}"
    os_like="${ID_LIKE:-$os}"
else
    echo "${red} Unable to detect the operating system ${reset}"
    exit 1
fi

# Convert operating system to lowercase
os=$(echo "${os:-unknown}" | tr '[:upper:]' '[:lower:]')
os_like=$(echo "$os_like" | tr '[:upper:]' '[:lower:]')

# Prints the detected operating system
echo "${green}Detected (ID): $os ${reset}"
echo "${green}Detected (ID_LIKE): $os_like ${reset}"

# Packages
packages=("package-name1")
aur_packages=("aur-package-name1")
flatpaks=("flatpak-name1")

# Executes commands based on the operating system
case "$os" in
    "arch")
        sudo pacman -S --needed --noconfirm "${packages[@]}"
        ;;
    "debian"|"ubuntu")
        sudo apt-get install -y "${packages[@]}"
        ;;
    "fedora"|"openmandriva")
        sudo dnf install -y "${packages[@]}"
        ;;
    "opensuse"*)
        sudo zypper in -y "${packages[@]}"
        ;;
    "void")
        sudo xbps-install -Sy "${packages[@]}"
    *)
        case "$os_like" in
            "arch")
                sudo pacman -S --needed --noconfirm "${packages[@]}"
                ;;
            "debian"|"ubuntu debian")
                sudo apt-get install -y "${packages[@]}"
                ;;
            "fedora")
                sudo dnf install -y "${packages[@]}"
                ;;
            "opensuse"*)
                sudo zypper in -y "${packages[@]}"
                ;;
            "void")
                sudo xbps-install -Sy "${packages[@]}"
            *)
                echo "${red}Unsupported distribution ${reset}"
                exit 1
                ;;
        esac
        ;;
esac
