#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# IF ELSE

# Checks for file system
if mount | grep -q "type apfs"; then
    echo "Detected File System: apfs"
fi

if mount | grep -q "type bcachefs"; then
    echo "Detected File System: bcachefs"
fi

if mount | grep -q "type btrfs"; then
    echo "Detected File System: btrfs"
fi

if mount | grep -q "type ext4"; then
    echo "Detected File System: ext4"
fi

if mount | grep -q "type f2fs"; then
    echo "Detected File System: f2fs"
fi

if mount | grep -q "type ntfs"; then
    echo "Detected File System: ntfs"
fi

if mount | grep -q "type vfat"; then
    echo "Detected File System: vfat"
fi

if mount | grep -q "type xfs"; then
    echo "Detected File System: xfs"
fi
            
if mount | grep -q "type zfs"; then
    echo "Detected File System: zfs"
fi

# CASE

# File systems
file_systems=(apfs bcachefs btrfs ext4 f2fs ntfs vfat xfs zfs)

# Executes commands based on the file system
for file_system in "${file_systems[@]}"; do
    case "$file_system" in
        "apfs")
            if mount | grep -q "type apfs"; then
                echo "Detected File System: apfs"
            fi
            ;;
        "bcachefs")
            if mount | grep -q "type bcachefs"; then
                echo "Detected File System: bcachefs"
            fi
            ;;
        "btrfs")
            if mount | grep -q "type btrfs"; then
                echo "Detected File System: btrfs"
            fi
            ;;
        "ext4")
            if mount | grep -q "type ext4"; then
                echo "Detected File System: ext4"
            fi
            ;;
        "f2fs")
            if mount | grep -q "type f2fs"; then
                echo "Detected File System: f2fs"
            fi
            ;;
        "ntfs")
            if mount | grep -q "type ntfs"; then
                echo "Detected File System: ntfs"
            fi
            ;;
        "vfat")
            if mount | grep -q "type vfat"; then
                echo "Detected File System: vfat"
            fi
            ;;
        "xfs")
            if mount | grep -q "type xfs"; then
                echo "Detected File System: xfs"
            fi
            ;;
        "zfs")
            if mount | grep -q "type zfs"; then
                echo "Detected File System: zfs"
            fi
            ;;
    esac
done
