#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# IF ELSE

# Define text colors
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
reset=$(tput sgr0)

# Checks for native file systems
if mount | grep -q "type bcachefs"; then
    echo "${green}Detected File System: bcachefs ${reset}"
else
    echo "${yellow}No bcachefs partitions detected ${reset}"
fi

if mount | grep -q "type btrfs"; then
    echo "${green}Detected File System: btrfs ${reset}"
else
    echo "${yellow}No btrfs partitions detected ${reset}"
fi

if mount | grep -q "type ext4"; then
    echo "${green}Detected File System: ext4 ${reset}"
else
    echo "${yellow}No ext4 partitions detected ${reset}"
fi

if mount | grep -q "type f2fs"; then
    echo "${green}Detected File System: f2fs ${reset}"
else
    echo "${yellow}No f2fs partitions detected ${reset}"
fi

if mount | grep -q "type xfs"; then
    echo "${green}Detected File System: xfs ${reset}"
else
    echo "${yellow}No xfs partitions detected ${reset}"
fi


# Check for non-native file systems
if mount | grep -q "type apfs"; then
    echo "${green}Detected File System: apfs ${reset}"
else
    echo "${yellow}No apfs partitions detected ${reset}"
fi

if mount | grep -q "type exfat"; then
    echo "${green}Detected File System: exfat ${reset}"
else
    echo "${yellow}No exfat partitions detected ${reset}"
fi

if mount | grep -q "type ntfs"; then
    echo "${green}Detected File System: ntfs ${reset}"
else
    echo "${yellow}No ntfs partitions detected ${reset}"
fi

if mount | grep -q "type vfat"; then
    echo "${green}Detected File System: vfat ${reset}"
else
    echo "${yellow}No vfat partitions detected ${reset}"
fi
            
if mount | grep -q "type zfs"; then
    echo "${green}Detected File System: zfs ${reset}"
else
    echo "${yellow}No zfs partitions detected ${reset}"
fi

# CASE

# Define text colors
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
reset=$(tput sgr0)

# File systems
file_systems=(apfs bcachefs btrfs ext4 f2fs ntfs vfat xfs zfs)

# Executes commands based on the file system
for file_system in "${file_systems[@]}"; do
    case "$file_system" in
        "apfs")
            if mount | grep -q "type apfs"; then
                echo "${green}Detected File System: $file_system ${reset}"
            else
                echo "${yellow}No $file_system partitions detected ${reset}"
            fi
            ;;
        "bcachefs")
            if mount | grep -q "type bcachefs"; then
                echo "${green}Detected File System: $file_system ${reset}"
            else
                echo "${yellow}No $file_system partitions detected ${reset}"
            fi
            ;;
        "btrfs")
            if mount | grep -q "type btrfs"; then
                echo "${green}Detected File System: $file_system ${reset}"
            else
                echo "${yellow}No $file_system partitions detected ${reset}"
            fi
            ;;
        "ext4")
            if mount | grep -q "type ext4"; then
                echo "${green}Detected File System: $file_system ${reset}"
            else
                echo "${yellow}No $file_system partitions detected ${reset}"
            fi
            ;;
        "f2fs")
            if mount | grep -q "type f2fs"; then
                echo "${green}Detected File System: $file_system ${reset}"
            else
                echo "${yellow}No $file_system partitions detected ${reset}"
            fi
            ;;
        "ntfs")
            if mount | grep -q "type ntfs"; then
                echo "${green}Detected File System: $file_system ${reset}"
            else
                echo "${yellow}No $file_system partitions detected ${reset}"
            fi
            ;;
        "vfat")
            if mount | grep -q "type vfat"; then
                echo "${green}Detected File System: $file_system ${reset}"
            else
                echo "${yellow}No $file_system partitions detected ${reset}"
            fi
            ;;
        "xfs")
            if mount | grep -q "type xfs"; then
                echo "${green}Detected File System: $file_system ${reset}"
            else
                echo "${yellow}No $file_system partitions detected ${reset}"
            fi
            ;;
        "zfs")
            if mount | grep -q "type zfs"; then
                echo "${green}Detected File System: $file_system ${reset}"
            else
                echo "${yellow}No $file_system partitions detected ${reset}"
            fi
            ;;
    esac
done
