#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# Define text colors
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
reset=$(tput sgr0)

# Checks for AMD GPU
if echo "$gpu_info" | grep -Fiq "amd"; then
    echo "${green}Detected GPU: AMD ${reset}"
else
    echo "${yellow}No AMD GPU detected. ${reset}"
fi

# Checks for Intel GPU
if echo "$gpu_info" | grep -Fiq "intel"; then
    echo "${green}Detected GPU: Intel ${reset}"
else
    echo "${yellow}No Intel GPU detected. ${reset}"
fi

# Checks for Nvidia GPU
if echo "$gpu_info" | grep -Fiq "nvidia"; then
    echo "${green}Detected GPU: Nvidia ${reset}"
else
    echo "${yellow}No Nvidia GPU detected. ${reset}"
fi
