#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# Get GPU information
gpu_info=$(lspci | grep -E "VGA|3D")

# Checks for AMD GPU
if echo "$gpu_info" | grep -iq "amd"; then
    echo "Detected GPU: AMD"
else
    echo "No AMD GPU detected"
fi

# Checks for Intel GPU
if echo "$gpu_info" | grep -iq "intel"; then
    echo "Detected GPU: Intel"
else
    echo "No Intel GPU detected"
fi

# Checks for Nvidia GPU
if echo "$gpu_info" | grep -iq "nvidia"; then
    echo "Detected GPU: Nvidia"
else
    echo "No Nvidia GPU detected"
fi
