#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# IF ELSE

# Checks for init system
if ps -p 1 -o comm= | grep -q "systemd"; then
    echo "Detected Init System: systemd"
    
elif ps -p 1 -o comm= | grep -q "runit"; then
    echo "Detected Init System: runit"
    
elif ps -p 1 -o comm= | grep -q "sysvinit"; then
    echo "Detected Init System: sysvinit"
    
elif ps -p 1 -o comm= | grep -q "openrc-init"; then
    echo "Detected Init System: openrc"
    
else
    echo "Unsupported init system"
    exit 1
fi

# CASE

# Get init information
init_info=$(ps -p 1 -o comm=)

# Executes commands based on the init system
case "$init_info" in
    "systemd")
        echo "Detected Init System: systemd"
        ;;
    "runit")
        echo "Detected Init System: runit"
        ;;
    "sysvinit")
        echo "Detected Init System: sysvinit"
        ;;
    "openrc-init")
        echo "Detected Init System: openrc"
        ;;
    *)
        echo "Unsupported init system: $init_info"
        exit 1
        ;;
esac
