#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# IF ELSE

# Define text colors
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
reset=$(tput sgr0)

# Define init system
if ps -p 1 -o comm= | grep -Fq "systemd"; then
    init_system="systemd"
    echo "${green}Detected Init System: $init_system ${reset}"
    
elif ps -p 1 -o comm= | grep -Fq "runit"; then
    init_system="runit"
    echo "${green}Detected Init System: $init_system ${reset}"
    
elif ps -p 1 -o comm= | grep -Fq "sysvinit"; then
    init_system="sysvinit"
    echo "${green}Detected Init System: $init_system ${reset}"
    
elif ps -p 1 -o comm= | grep -Fq "openrc-init"; then
    init_system="openrc-init"
    echo "${green}Detected Init System: $init_system ${reset}"
    
else
    init_system="unknown"
fi

# Checks for init system and enables service
if [ "$init_system" = "systemd" ]; then
    sudo systemctl enable --now package.service

elif [ "$init_system" = "runit" ]; then
    echo "${green}Detected Init System: $init_system ${reset}"
    sudo ln -s /etc/sv/package /var/service
else
    echo "{$red}Unsupported init system ${reset}"
    exit 1
fi

# CASE

# Define text colors
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
reset=$(tput sgr0)

# Get init system
init_system=$(ps -p 1 -o comm=)

# Executes commands based on the init system
case "$init_system" in
    "systemd")
        echo "${green}Detected Init System: $init_system ${reset}"
        ;;
    "runit")
        echo "${green}Detected Init System: $init_system ${reset}"
        ;;
    "sysvinit")
        echo "${green}Detected Init System: $init_system ${reset}"
        ;;
    "openrc-init")
        echo "${green}Detected Init System: $init_system ${reset}"
        ;;
    *)
        echo "${red}Unsupported init system: $init_system ${reset}"
        exit 1
        ;;
esac
