#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# IF ELSE

# Text formatting
red=$(tput setaf 1)
green=$(tput setaf 2)
reset=$(tput sgr0)

# Checks for init system
if ps -p 1 -o comm= | grep -q "systemd"; then
    echo "${green}Detected Init System: systemd ${reset}"
    
elif ps -p 1 -o comm= | grep -q "runit"; then
    echo "${green}Detected Init System: runit ${reset}"
    
elif ps -p 1 -o comm= | grep -q "sysvinit"; then
    echo "${green}Detected Init System: sysvinit ${reset}"
    
elif ps -p 1 -o comm= | grep -q "openrc-init"; then
    echo "${green}Detected Init System: openrc ${reset}"
    
else
    echo "${red}Unsupported init system ${reset}"
    exit 1
fi

# CASE

# Text formatting
red=$(tput setaf 1)
green=$(tput setaf 2)
reset=$(tput sgr0)

# Get init information
init_info=$(ps -p 1 -o comm=)

# Executes commands based on the init system
case "$init_info" in
    "systemd")
        echo "${green}Detected Init System: systemd ${reset}"
        ;;
    "runit")
        echo "${green}Detected Init System: runit ${reset}"
        ;;
    "sysvinit")
        echo "${green}Detected Init System: sysvinit ${reset}"
        ;;
    "openrc-init")
        echo "${green}Detected Init System: openrc ${reset}"
        ;;
    *)
        echo "${red}Unsupported init system: $init_info ${reset}"
        exit 1
        ;;
esac
