#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# Define text colors
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
reset=$(tput sgr0)

# Checks for optical drive
if [ -e /dev/sr0 ]; then
    echo "${green}Optical drive detected ${reset}"
else
    echo "${yellow}No optical drive detected ${reset}"
fi
