#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# IF ELSE

# Packages
packages=("package")
aur_packages=("package")
flatpaks=("flatpak")

# Checks for package manager
if command -v apt > /dev/null 2>&1; then
    echo "Detected: apt"
    # Installs package(s)
    sudo apt-get install -y "${packages[@]}"

elif command -v dnf > /dev/null 2>&1; then
    echo "Detected: dnf"
    # Installs package(s)
    sudo dnf install -y "${packages[@]}"

elif command -v pacman > /dev/null 2>&1; then
    echo "Detected: pacman"
    # Installs package(s)
    sudo pacman -S --needed --noconfirm "${packages[@]}"
    if command -v paru > /dev/null 2>&1; then
        echo "Detected: paru"
        # Installs package(s)
        paru -S "${aur_packages[@]}"
    elif command -v yay > /dev/null 2>&1; then
        echo "Detected: yay"
        # Installs package(s)
        yay -S "${aur_packages[@]}"
    else
        # Installs package(s)
        sudo pacman -S --needed --noconfirm base-devel git makepkg
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si --noconfirm
        cd ..
        rm -rf yay
        yay -S "${aur_packages[@]}"
    fi

elif command -v xbps-install > /dev/null 2>&1; then
    echo "Detected: xbps"
    # Installs package(s)
    sudo xbps-install -Sy "${packages[@]}"

elif command -v zypper > /dev/null 2>&1; then
    echo "Detected: zypper"
    # Installs package(s)
    sudo zypper in -y "${packages[@]}"

elif command -v flatpak > /dev/null 2>&1; then
    echo "Detected: flatpak"
    # Installs package(s)
    flatpak install flathub -y "${flatpaks[@]}"

elif command -v snap > /dev/null 2>&1; then
    echo "Detected: snap"
    # Installs package(s)
    sudo snap install "${packages[@]}"

elif command -v rpm-ostree > /dev/null 2>&1; then
    echo "Detected: rpm-ostree"
    # Installs package(s)
    sudo rpm-ostree install "${packages[@]}"

else
    echo "Unsupported package manager"
    exit 1
fi

# CASE

# Text formatting
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
reset=$(tput sgr0)

# Packages
packages=("package")
aur_packages=("package")
flatpaks=("flatpak")

# Package managers
managers=("apt" "dnf" "pacman" "paru" "yay" "xbps-install" "zypper" "flatpak" "snap" "rpm-ostree")

# Loops through package managers
for manager in "${managers[@]}"; do
    if command -v "$manager" > /dev/null 2>&1; then
        echo "Detected: $manager"
        case "$manager" in
            "apt")
                echo "${green}Installing package using $manager...${reset}"
                # Installs package(s)
                sudo apt-get install -y "${packages[@]}"
                ;;
            "dnf")
                echo "${green}Installing package using $manager...${reset}"
                # Installs package(s)
                sudo dnf install -y "${packages[@]}"
                ;;
            "pacman")
                echo "${green}Installing package using $manager...${reset}"
                # Installs package(s)
                sudo pacman -S --needed --noconfirm "${packages[@]}"
                ;;
            "paru")
                echo "${green}Installing package using $manager...${reset}"
                # Installs package(s)
                paru -S "${aur_packages[@]}"
                ;;
            "yay")
                echo "${green}Installing package using $manager...${reset}"
                # Installs package(s)
                yay -S "${aur_packages[@]}"
                ;;
            "xbps-install")
                echo "${green}Installing package using $manager...${reset}"
                # Installs package(s)
                sudo xbps-install -Sy "${packages[@]}"
                ;;
            "zypper")
                echo "${green}Installing package using $manager...${reset}"
                # Installs package(s)
                sudo zypper in -y "${packages[@]}"
                ;;
            "flatpak")
                echo "${green}Installing package using $manager...${reset}"
                # Installs package(s)
                flatpak install flathub -y "${flatpaks[@]}"
                ;;
            "snap")
                echo "${green}Installing package using $manager...${reset}"
                # Installs package(s)
                sudo snap install "${packages[@]}"
                ;;
            "rpm-ostree")
                echo "${green}Installing package using $manager...${reset}"
                # Installs package(s)
                sudo rpm-ostree install "${packages[@]}"
                ;;
        esac
    fi
done

echo "Unsupported package manager"
exit 1
