#!/usr/bin/env bash

# Sets the script to exit immediately when any error, unset variable, or pipeline failure occurs
set -euo pipefail

# IF ELSE

# Text formatting
red=$(tput setaf 1)
green=$(tput setaf 2)
reset=$(tput sgr0)

# Packages
packages=(
"package1"
"package2"
)

aur_packages=(
"package1"
"package2"
)

flatpaks=(
"flatpak1"
"flatpak2"
)

# Checks for package manager
if command -v apt > /dev/null 2>&1; then
    echo "${green}Detected Package Manager: apt ${reset}"
    # Installs package(s)
    sudo apt-get install -y "${packages[@]}"

elif command -v dnf > /dev/null 2>&1; then
    echo "${green}Detected Package Manager: dnf ${reset}"
    # Installs package(s)
    sudo dnf install -y "${packages[@]}"

elif command -v pacman > /dev/null 2>&1; then
    echo "${green}Detected Package Manager: pacman ${reset}"
    # Installs package(s)
    sudo pacman -S --needed --noconfirm "${packages[@]}"
    if command -v paru > /dev/null 2>&1; then
        echo "${green}Detected Package Manager: paru ${reset}"
        # Installs package(s)
        paru -S "${aur_packages[@]}"
    elif command -v yay > /dev/null 2>&1; then
        echo "${green}Detected Package Manager: yay ${reset}"
        # Installs package(s)
        yay -S "${aur_packages[@]}"
    else
        # Installs package(s)
        sudo pacman -S --needed --noconfirm base-devel git makepkg
        git clone https://aur.archlinux.org/paru.git
        cd paru
        makepkg -si --noconfirm
        cd ..
        rm -rf paru
        paru -S "${aur_packages[@]}"
    fi

elif command -v xbps-install > /dev/null 2>&1; then
    echo "${green}Detected Package Manager: xbps ${reset}"
    # Installs package(s)
    sudo xbps-install -Sy "${packages[@]}"

elif command -v zypper > /dev/null 2>&1; then
    echo "${green}Detected Package Manager: zypper ${reset}"
    # Installs package(s)
    sudo zypper in -y "${packages[@]}"

elif command -v flatpak > /dev/null 2>&1; then
    echo "${green}Detected Package Manager: flatpak ${reset}"
    # Installs package(s)
    flatpak install flathub -y "${flatpaks[@]}"

elif command -v snap > /dev/null 2>&1; then
    echo "${green}Detected Package Manager: snap ${reset}"
    # Installs package(s)
    sudo snap install "${packages[@]}"

elif command -v rpm-ostree > /dev/null 2>&1; then
    echo "${green}Detected Package Manager: rpm-ostree ${reset}"
    # Installs package(s)
    sudo rpm-ostree install "${packages[@]}"

else
    echo "${red}Unsupported package manager ${reset}"
    exit 1
fi

# CASE

# Text formatting
red=$(tput setaf 1)
green=$(tput setaf 2)
reset=$(tput sgr0)

# Packages
packages=(
"package1"
"package2"
)

aur_packages=(
"package1"
"package2"
)

flatpaks=(
"flatpak1"
"flatpak2"
)

# Package managers
managers=(apt dnf pacman paru yay xbps-install zypper flatpak snap rpm-ostree)

# Loops through package managers
for manager in "${managers[@]}"; do
    if command -v "$manager" > /dev/null 2>&1; then
        echo "Detected: $manager"
        case "$manager" in
            "apt")
                echo "${green}Installing package(s) using $manager... ${reset}"
                # Installs package(s)
                sudo apt-get install -y "${packages[@]}"
                ;;
            "dnf")
                echo "${green}Installing package(s) using $manager... ${reset}"
                # Installs package(s)
                sudo dnf install -y "${packages[@]}"
                ;;
            "pacman")
                echo "${green}Installing package(s) using $manager... ${reset}"
                # Installs package(s)
                sudo pacman -S --needed --noconfirm "${packages[@]}"
                ;;
            "paru")
                echo "${green}Installing package(s) using $manager... ${reset}"
                # Installs package(s)
                paru -S "${aur_packages[@]}"
                ;;
            "yay")
                echo "${green}Installing package(s) using $manager... ${reset}"
                # Installs package(s)
                yay -S "${aur_packages[@]}"
                ;;
            "xbps-install")
                echo "${green}Installing package(s) using $manager... ${reset}"
                # Installs package(s)
                sudo xbps-install -Sy "${packages[@]}"
                ;;
            "zypper")
                echo "${green}Installing package(s) using $manager... ${reset}"
                # Installs package(s)
                sudo zypper in -y "${packages[@]}"
                ;;
            "flatpak")
                echo "${green}Installing package(s) using $manager... ${reset}"
                # Installs package(s)
                flatpak install flathub -y "${flatpaks[@]}"
                ;;
            "snap")
                echo "${green}Installing package(s) using $manager... ${reset}"
                # Installs package(s)
                sudo snap install "${packages[@]}"
                ;;
            "rpm-ostree")
                echo "${green}Installing package(s) using $manager... ${reset}"
                # Installs package(s)
                sudo rpm-ostree install "${packages[@]}"
                ;;
        esac
    else
        echo "${red}Unsupported package manager ${reset}"
        exit 1
    fi
done
