# Reclaim policy
vm.swappiness = 20

# Swap-out write granularity
vm.page-cluster = 3

# Compaction subsystem
vm.compaction_proactiveness = 0
vm.extfrag_threshold = 1000

# Writeback subsystem
vm.dirty_background_ratio = 10
vm.dirty_ratio = 20
vm.dirty_writeback_centisecs = 1500

# Reclaim thresholds
vm.vfs_cache_pressure = 100
vm.watermark_boost_factor = 0
vm.watermark_scale_factor = 125

# Global VM limits
vm.max_map_count = 1048576
