# Reclaim policy
vm.swappiness = 40

# Swap-out write granularity
vm.page-cluster = 1

# Compaction subsystem
vm.compaction_proactiveness = 10
vm.extfrag_threshold = 750

# Writeback subsystem
vm.dirty_background_ratio = 5
vm.dirty_ratio = 10

# Reclaim thresholds
vm.vfs_cache_pressure = 100
vm.watermark_boost_factor = 0
vm.watermark_scale_factor = 125

# Global VM limits
vm.max_map_count = 1048576
