# Load ld_bash.d runtime environment
ld_bash_dir="$HOME/.ld_bash.d"

shopt -s nullglob globstar
for file in "$ld_bash_dir"/**/*.sh; do
    [ -e "$file" ] || continue
    . "$file"
done
shopt -u nullglob globstar
