# Video profile
profile=high-quality

# Enable hardware decoding
--hwdec=auto

# Audio filter
af=lavfi=[loudnorm=I=-20:LRA=8:tp=-2:linear=false]

# Set the default audio and subtitle language
#alang=eng
slang=eng
sub-auto=fuzzy

# Set the default audio and subtitle track number
#aid=2
#sid=2
